name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Build
        run: bazel build @fabazel//mod/src/main:mod --verbose_failures
      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          compression-level: 9
          if-no-files-found: error
          path: bazel-bin/mod/src/main/mod.jar
